name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb3fb4fa6fe58d461b8fe898d96c5438859d872a8e85b0ef2fa69d2a6461233c"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
