name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9730877f421a04c59fcbe9576abad27f530f433870622f690fdc1d7c56b9d621"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.2"
