name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "025174f4f088e973586f903004acce648eb86e388f484abdd7a6055b0c68fd3d"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0-beta.2"
