name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "978940eb9e15fad87c770e0ecbb5592e105130398d203fce0d858352fc5ddee7"

[versions]
minecraft = "1.18.2"
quilt = "0.17.3"
