name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe055e0fd94c3d0c3e3e756ec67d7beda7c53cfc4e8ad32ff492a92e584afe0f"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1-beta.3"
