name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1b3cbf9867bace5239b729c5638ecfb7201fc4a8b59f84f10a475b4d052709aa"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1-beta.3"
