name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0bd90e24f30110c9847b107e50d26b3d4715370eb6bcb3566c23148e8c726271"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1-beta.3"
