name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0c85864e3c146fb18723c2385f23b6e9716555b714e0eeeba1f4c003f559f83"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.6"
