name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3f2b3aa6493aa5d1f37d57428c4078fbd99a1bdc7903a2f536ee289f7bbe0b54"

[versions]
minecraft = "1.18.2"
quilt = "0.17.3"
