name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "13aba8b74288413c1f15879d78ff0fc55c95eb75452d6973522ff616ca3dd169"

[versions]
minecraft = "1.18.2"
quilt = "0.17.0-beta.2"
