name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddf67ccaf07163ec27ce1a07015085ef468abb186b2b155bbe135d287094bb17"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.4"
