name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a6ae6f267be060fc30ea6ca38613012607fb5f709a84de60c1d7a4b8e20beea"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1-beta.3"
