name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba76682ff4e60ee35e2be1cfab6d8eaeaba51cb09240b3528ed0c01cac4fda92"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.2"
