name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9d5cb702e20fee1695a64aace5d0ad69064d5f260950cc477db1bccf6d1579f7"

[versions]
minecraft = "1.18.2"
quilt = "0.17.1-beta.2"
