name = "Innovation Timespace 5"
author = "Kneelawk"
version = "0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "168fd29aa3e9fcdd816e15c8007f78bf714cdbf9dc7749ce6c9bded6b9f11b8a"

[versions]
minecraft = "1.18.2"
quilt = "0.16.1"
