name = "Adorn"
filename = "Adorn-3.5.0+1.18.2-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/E6FUtRJh/versions/3.5.0-fabric/Adorn-3.5.0%2B1.18.2-fabric.jar"
hash-format = "sha1"
hash = "54dc846236010b1e22bfdb6b7d06a669f6ccfb5a"

[update]
[update.modrinth]
mod-id = "E6FUtRJh"
version = "6N5U8wzl"
