name = "Applied Energistics 2 Wireless Terminals"
filename = "AE2WTLib-11.0.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/pNabrMMw/versions/11.0.1-fabric/AE2WTLib-11.0.1.jar"
hash-format = "sha1"
hash = "3623c8276eda39d76353f5fe70ec4cd9575c30db"

[update]
[update.modrinth]
mod-id = "pNabrMMw"
version = "uMnxfT7w"
