name = "AppleSkin"
filename = "appleskin-fabric-mc1.18.2-2.4.0.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "07cc0f6d00b184bef9c4390682c098d5ca52e67d"
url = "https://cdn.modrinth.com/data/EsAfCjCV/versions/fabric-mc1.18.2-2.4.0/appleskin-fabric-mc1.18.2-2.4.0.jar"

[update.modrinth]
mod-id = "EsAfCjCV"
version = "gQRJj49P"
