name = "Applied Energistics 2 Wireless Terminals"
filename = "AE2WTLib-11.1.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/pNabrMMw/versions/11.1.1-fabric/AE2WTLib-11.1.1.jar"
hash-format = "sha1"
hash = "57bfe9ad3e2eaf5ddc84fdf6a614e501643a244e"
mode = ""

[update]
[update.modrinth]
mod-id = "pNabrMMw"
version = "JAkNTbad"
