name = "Bits And Chisels"
filename = "bitsandchisels-2.6.9.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/q8MC5tW2/versions/2.6.9/bitsandchisels-2.6.9.jar"
hash-format = "sha1"
hash = "c2b5b1f41a4295bfe8b11c02b7932577c8a97db4"
mode = ""

[update]
[update.modrinth]
mod-id = "q8MC5tW2"
version = "KnMJJ3iN"
