name = "Blossom"
filename = "blossom-1.18.2-1.0.4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/iYVih5qu/versions/1.0.4/blossom-1.18.2-1.0.4.jar"
hash-format = "sha1"
hash = "6f6abddca35676717c7279df3f5602da5706999a"

[update]
[update.modrinth]
mod-id = "iYVih5qu"
version = "Vv5gJ9jD"
