name = "CC: Restitched"
filename = "cc-restitched-1.100.6.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/eldBwa5V/versions/1.100.6/cc-restitched-1.100.6.jar"
hash-format = "sha1"
hash = "2fa8a582d7fef34fbf1ed4e2cc8cb25b9c35ccb5"
mode = ""

[update]
[update.modrinth]
mod-id = "eldBwa5V"
version = "cFI8wbhG"
