name = "Cloth Config API"
filename = "cloth-config-6.2.57-fabric.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "994915e00e2900453ec6478f920a87bf10ac9d05"
url = "https://cdn.modrinth.com/data/9s6osm5g/versions/6.2.57+fabric/cloth-config-6.2.57-fabric.jar"

[update.modrinth]
mod-id = "9s6osm5g"
version = "63NArvT8"
