name = "Consistency+"
filename = "consistency_plus-fabric-0.5.0+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/nDHcEOt3/versions/xugTWp2u/consistency_plus-fabric-0.5.0%2B1.18.2.jar"
hash-format = "sha1"
hash = "f73c575de028148be27e4caf51794de8705aea66"

[update]
[update.modrinth]
mod-id = "nDHcEOt3"
version = "xugTWp2u"
