name = "Conveyor Belts"
filename = "conveyor-belts-1.8.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/WjHeCvm0/versions/1.8/conveyor-belts-1.8.jar"
hash-format = "sha1"
hash = "2afbd6f909431280e32f40f02f5b07b5a19db260"

[update]
[update.modrinth]
mod-id = "WjHeCvm0"
version = "vLWebMRv"
