name = "Create Fabric"
filename = "create-mc1.18.2_v0.4.1+565.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/Xbc0uyRg/versions/mc1.18.2_v0.4.1/create-mc1.18.2_v0.4.1%2B565.jar"
hash-format = "sha1"
hash = "d3c3312e51bcf036703f94fb14bdbdbb30202d9c"

[update]
[update.modrinth]
mod-id = "Xbc0uyRg"
version = "mRXoRTy0"
