name = "Dark Enchanting"
filename = "dark-enchanting-1.0.0+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/6M87Z355/versions/1.0.0+1.18.2/dark-enchanting-1.0.0%2B1.18.2.jar"
hash-format = "sha1"
hash = "854bde1252f7f01836bbfbef1cdd8286c0ce1fd3"

[update]
[update.modrinth]
mod-id = "6M87Z355"
version = "LWAGIiVU"
