name = "Dawn API"
filename = "dawn-3.3.1.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/meZK2DCX/versions/3.3.1/dawn-3.3.1.jar"
hash-format = "sha1"
hash = "bd15a7bff39ac57ca825557eadc388111cc559f1"
mode = ""

[update]
[update.modrinth]
mod-id = "meZK2DCX"
version = "rJ2vYNjm"
