name = "Dawn API"
filename = "dawn-3.3.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/meZK2DCX/versions/3.3.0/dawn-3.3.0.jar"
hash-format = "sha1"
hash = "e6a97045ec54148d83c2222760360b34362ee374"

[update]
[update.modrinth]
mod-id = "meZK2DCX"
version = "8FVAcXqk"
