name = "Essential Commands"
filename = "essential_commands-0.24.5-mc1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/6VdDUivB/versions/0.24.5-mc1.18.2/essential_commands-0.24.5-mc1.18.2.jar"
hash-format = "sha1"
hash = "6d117b9aaf87f668650b31b4c678abe188c430d0"

[update]
[update.modrinth]
mod-id = "6VdDUivB"
version = "hasuJFnp"
