name = "Extended Drawers"
filename = "ExtendedDrawers-1.2.1+mc.1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/AhtxbnpG/versions/1.2.1/ExtendedDrawers-1.2.1%2Bmc.1.18.2.jar"
hash-format = "sha1"
hash = "c4262021ee3bc9bacc37f41a9cb58b5727ff8c2c"
mode = ""

[update]
[update.modrinth]
mod-id = "AhtxbnpG"
version = "DxmhwMW6"
