name = "Fabric Waystones"
filename = "wraith-waystones-2.5.4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/sTZr7NVo/versions/2.5.4/wraith-waystones-2.5.4.jar"
hash-format = "sha1"
hash = "66dfb3c444db9d59317a1670859937e04c584f69"
mode = ""

[update.modrinth]
mod-id = "sTZr7NVo"
version = "FfIP51Fl"
