name = "Fabric Waystones"
filename = "wraith-waystones-2.5.3.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "9a20e854631aeaa117067f8687c79aae7ffb70ff"
url = "https://cdn.modrinth.com/data/sTZr7NVo/versions/2.5.3/wraith-waystones-2.5.3.jar"

[update.modrinth]
mod-id = "sTZr7NVo"
version = "iFyo0sjK"
