name = "Get Off My Lawn ReServed"
filename = "goml-1.5.0-beta.5+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/j5niDupl/versions/1.5.0-beta.5+1.18.2/goml-1.5.0-beta.5%2B1.18.2.jar"
hash-format = "sha1"
hash = "eba29f52cd834ef82fd197e1eb6f6fe7ccd931f5"

[update]
[update.modrinth]
mod-id = "j5niDupl"
version = "jHWTWpri"
