name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18.2-1.4.0.jar"
side = "client"

[download]
hash-format = "sha1"
hash = "e64426b95a2997ea4e6a31884401697a2040b888"
url = "https://cdn.modrinth.com/data/O7RBXm3n/versions/fabric-1.18.2-1.4.0/InventoryProfilesNext-fabric-1.18.2-1.4.0.jar"

[update.modrinth]
mod-id = "O7RBXm3n"
version = "9DtzZBh4"
