name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18.2-1.6.5.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/O7RBXm3n/versions/yN4h9Kop/InventoryProfilesNext-fabric-1.18.2-1.6.5.jar"
hash-format = "sha1"
hash = "6e73736cd5d28fe7f1b559423d7ed87b8ea9794a"

[update]
[update.modrinth]
mod-id = "O7RBXm3n"
version = "yN4h9Kop"
