name = "Inventory Profiles Next"
filename = "InventoryProfilesNext-fabric-1.18.2-1.3.8.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/O7RBXm3n/versions/fabric-1.18.2-1.3.8/InventoryProfilesNext-fabric-1.18.2-1.3.8.jar"
hash-format = "sha1"
hash = "029a26c70e811469aebf6da23d59f1cfb8a83509"

[update]
[update.modrinth]
mod-id = "O7RBXm3n"
version = "CyFD4N5J"
