name = "Lithium"
filename = "lithium-fabric-mc1.18.2-0.7.9.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "2f0298476ba54e8fc640c9bfe132a193db45b92b"
url = "https://cdn.modrinth.com/data/gvQqBUqZ/versions/mc1.18.2-0.7.9/lithium-fabric-mc1.18.2-0.7.9.jar"

[update.modrinth]
mod-id = "gvQqBUqZ"
version = "MoF1cn6g"
