name = "Minecraft Transit Railway"
filename = "MTR-fabric-1.18.2-3.0.0.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "cadfce32951d02ffb33c029d9efc4344ed06cba6"
url = "https://cdn.modrinth.com/data/XKPAmI6u/versions/1.18.2-3.0.0/MTR-fabric-1.18.2-3.0.0.jar"

[update.modrinth]
mod-id = "XKPAmI6u"
version = "7zzkD8Ha"
