name = "NinjaPhenix's Container Library"
filename = "ninjaphenix-container-library-1.3.0+1.18-fabric.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/TIhTvPdy/versions/1.3.0+1.18-fabric/ninjaphenix-container-library-1.3.0%2B1.18-fabric.jar"
hash-format = "sha1"
hash = "32670d31b6ae25dc1bf5683983362a3ad97223e5"

[update]
[update.modrinth]
mod-id = "TIhTvPdy"
version = "UA9i2a9a"
