name = " Paradise Lost"
filename = "paradise-lost-1.6.8+1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "cff462692aec7748129ec3c36c73f0d27aa1ed01"
url = "https://cdn.modrinth.com/data/IKpsG0nF/versions/1.6.8/paradise-lost-1.6.8%2B1.18.2.jar"

[update.modrinth]
mod-id = "IKpsG0nF"
version = "zfgH9Tea"
