name = "Phonos"
filename = "phonos-0.3+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/z5KH0yKE/versions/0.3+1.18.2/phonos-0.3%2B1.18.2.jar"
hash-format = "sha1"
hash = "630d22de4db2e7a9a11e17798537df4a7a84646c"

[update]
[update.modrinth]
mod-id = "z5KH0yKE"
version = "Ixgxkdcc"
