name = "Portal Cubed"
filename = "portal_cubed-2.2.4.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/GUwDZ4ZU/versions/2.2.4+quilt/portal_cubed-2.2.4.jar"
hash-format = "sha1"
hash = "c7fb5b9ec8e974dad4e606abeb53a360abcf2097"
mode = ""

[update]
[update.modrinth]
mod-id = "GUwDZ4ZU"
version = "gVuuYflE"
