name = "Quilt Standard Libraries"
filename = "qsl-1.1.0-beta.14_qfapi-1.0.0-beta.17_fapi-0.54.0_mc-1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/qvIfYCYJ/versions/1.0.0-beta.17+0.54.0-1.18.2/qsl-1.1.0-beta.14_qfapi-1.0.0-beta.17_fapi-0.54.0_mc-1.18.2.jar"
hash-format = "sha1"
hash = "28758cad7fedde50bdaa6f3ef03dfda5b3bb02ae"
mode = ""

[update]
[update.modrinth]
mod-id = "qvIfYCYJ"
version = "lz767pA6"
