name = "QuickCarpet"
filename = "quickcarpet-3.5.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/dqrpBD4O/versions/3.5.0/quickcarpet-3.5.0.jar"
hash-format = "sha1"
hash = "cae7ee92acca7ba468a04f9e914252e8d7754297"
mode = ""

[update.modrinth]
mod-id = "dqrpBD4O"
version = "WpVB9efm"
