name = "Redstone Bits"
filename = "redstone-bits-1.8.1+fabric-mc1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/4RK1aHVB/versions/1.8.1/redstone-bits-1.8.1%2Bfabric-mc1.18.2.jar"
hash-format = "sha1"
hash = "8b0653659f60e57a014a72fb870ce5d3a21fa58e"
mode = ""

[update]
[update.modrinth]
mod-id = "4RK1aHVB"
version = "IlRlOcdP"
