name = "Reese's Sodium Options"
filename = "reeses_sodium_options-mc1.18.2-1.4.2.jar"
side = "client"

[download]
hash-format = "sha1"
hash = "eecfa116802f89921e1b3a11f14240a08b97573b"
url = "https://cdn.modrinth.com/data/Bh37bMuy/versions/mc1.18.2-1.4.2/reeses_sodium_options-mc1.18.2-1.4.2.jar"

[update.modrinth]
mod-id = "Bh37bMuy"
version = "IUZ9L8mF"
