name = "Repurposed Structures - Fabric"
filename = "repurposed_structures_fabric-4.1.8+1.18.2.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "20a642ee7f96c1dde9c4d3d66585f5b1713b7506"
url = "https://cdn.modrinth.com/data/muf0XoRe/versions/4.1.8+1.18.2/repurposed_structures_fabric-4.1.8%2B1.18.2.jar"

[update.modrinth]
mod-id = "muf0XoRe"
version = "CGkSggJi"
