name = "Repurposed Structures - Fabric"
filename = "repurposed_structures_fabric-4.1.12+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/muf0XoRe/versions/4.1.12+1.18.2/repurposed_structures_fabric-4.1.12%2B1.18.2.jar"
hash-format = "sha1"
hash = "69701588256e96e840ee6470d61e839d79409311"
mode = ""

[update]
[update.modrinth]
mod-id = "muf0XoRe"
version = "Vf829t9B"
