name = "Sandwichable"
filename = "sandwichable-1.2+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/5g7OOxWC/versions/1.2+1.18.2/sandwichable-1.2%2B1.18.2.jar"
hash-format = "sha1"
hash = "92c9bbb38ce2624eabb18749b30746b638fa93b8"

[update]
[update.modrinth]
mod-id = "5g7OOxWC"
version = "ZwoaPnoN"
