name = "slotlink"
filename = "slotlink-4.3.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/FTMcNdhv/versions/4.3.2/slotlink-4.3.2.jar"
hash-format = "sha1"
hash = "466afb9600d3cd6aa46ebe656127be39f7322d23"

[update]
[update.modrinth]
mod-id = "FTMcNdhv"
version = "IYjMma1x"
