name = "Universal Ores"
filename = "universal_ores-1.3.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/68kWHuUF/versions/1.3.0/universal_ores-1.3.0.jar"
hash-format = "sha1"
hash = "0aa31446e22e049248cd8fad90cb2050f1fd06a2"

[update]
[update.modrinth]
mod-id = "68kWHuUF"
version = "b18AFuxC"
