name = "Useless Things"
filename = "uselessthings-1.1.0.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/NEeuMhS3/versions/1.1.0/uselessthings-1.1.0.jar"
hash-format = "sha1"
hash = "0b0028b7da31eaab154796333c2d7fb0b6f3376b"
mode = ""

[update.modrinth]
mod-id = "NEeuMhS3"
version = "FCxQvZet"
