name = "Wired Redstone"
filename = "wired-redstone-0.3.6+1.18.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/lyYGrdho/versions/0.3.6+1.18.2/wired-redstone-0.3.6%2B1.18.2.jar"
hash-format = "sha1"
hash = "2d38d3fec4c2e2f6522e11b682e5bf637b14f6db"

[update]
[update.modrinth]
mod-id = "lyYGrdho"
version = "qS9WRLIt"
