name = "Wired Redstone"
filename = "wired-redstone-0.2.3.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "4399ea9874649f90eabf96e5d3a5071b51df9322"
url = "https://cdn.modrinth.com/data/lyYGrdho/versions/0.2.3/wired-redstone-0.2.3.jar"

[update.modrinth]
mod-id = "lyYGrdho"
version = "V7qtUNpb"
