name = "WTHIT"
filename = "wthit-fabric-4.10.3.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "014f61ffa930eaf41dd48156e97dde63abe08327"
url = "https://cdn.modrinth.com/data/6AQIaxuO/versions/fabric-4.10.3/wthit-fabric-4.10.3.jar"

[update.modrinth]
mod-id = "6AQIaxuO"
version = "IPNj6sXo"
