name = "You're in Grave Danger"
filename = "youre-in-grave-danger-1.3.5.jar"
side = "both"

[download]
hash-format = "sha1"
hash = "dc403bc87793ec7a10341d6bfe5835b7d8658ade"
url = "https://cdn.modrinth.com/data/HnD1GX6e/versions/1.3.5/youre-in-grave-danger-1.3.5.jar"

[update.modrinth]
mod-id = "HnD1GX6e"
version = "Xzvp4zMi"
